# Generated by Django 5.2.4 on 2025-08-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thou', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
